### ISSUE TITLE
Regenerate on file save when using npm run serve

### ISSUE THREAD

**Issue by meirroth** [GTANAdam/vue-fontawesome-autogen#1]
Thank you very much for creating this useful plugin!
Works flawlessly in my Vue 3 project.

Q:
How can I modify the [vue config file](https://github.com/GTANAdam/vue-fontawesome-autogen/blob/main/example/vue.config.js#L11) to run autogen on file save when in serve mode?
I tried changing the param `['run']` to `['watchRun']` and to `['beforeCompile']` and it just went into an Infinite rebuild loop.

**Comment by GTANAdam** [comment]
Greetings! I have stumbled upon this a couple of times but I had decided to include the whole fontawesome library when debugging to save time, but I will definitely have a look into this because the script changes the file while vue serve mode keeps watching file changes so it becomes a loop.

**Comment by M1CK431** [comment]
Hi @meirroth 

I have fix this issue (among others) here: #6 
Now waiting for @GTANAdam review/merge :crossed_fingers: 

Cheers! :kissing:

**Comment by meirroth** [comment]
@M1CK431 Thank you!!
