### ISSUE TITLE
Won't recognize icon if more than one whitespace character after opening tag

### ISSUE THREAD

**Issue by meirroth** [GTANAdam/vue-fontawesome-autogen#2]
The autogen wont recognize the icon if there is more than one whitespace character after the opening tag,
Here are two examples:
1.
`<fa`_more than one whitespace_`icon="fas-info-circle" />`
2.
```
<fa
  icon="fas-info-circle"
  ....
/>
```

Looking through the source code I see there is a regex on line 23:
`/(?<=<fa\sicon="+).*?(?=")/g` 
adding a plus quantifier after the `\s` meta escape, solves this issue.
See [before](https://regex101.com/r/kYdYDD/1) and [after](https://regex101.com/r/d605jt/1) on regex101.com

**Comment by GTANAdam** [comment]
Greetings, thank you for bringing attention to this, could you please submit a pull request?

**Comment by meirroth** [comment]
Sure!
